gantt
    title Optimal Transmission Times for Each Band (EST & UTC)
    dateFormat  HH:mm
    axisFormat  %H:%M

    section Optimal Times (EST)
    Optimal Window 160 meters :active, 00:00, 06h    
    160 meters :opt1, 00:00, 03h

    Optimal Window 80 meters :active, 00:00, 06h
    80 meters :opt1, 03:00, 03h

    Optimal Window 20 meters :active, 09:00, 09h    
    20 meters :opt1, 16:00, 01h
    Transmit :opt1, 09:00, 01h
    Transmit :opt2, 17:00, 03h

    Optimal Window 60 meters :active, 22:00, 02h
    Optimal Window 60 meters :active, 00:00, 06h        
    60 meters :opt1, 22:00, 02h

    Optimal Window 40 meters :active, 20:00, 4h
    Optimal Window 40 meters :active, 00:00, 9h
    40 meters :opt1, 20:00, 2h

    Optimal Window 30 meters :active, 19:00, 5h
    Optimal Window 30 meters :active, 00:00, 9h
    30 meters :opt1, 06:00, 3h
    
    Optimal Window 15 meters :active, 10:00, 04h
    15 meters :opt1, 10:00, 02h

    Optimal Window 17 meters :active, 10:00, 06h
    17 meters :opt1, 14:00, 01h

    Optimal Window 10 meters :active, 10:00, 04h
    10 meters :opt1, 12:00, 01h

    Optimal Window 2 meters :active, 11:00, 05h
    2 meters :opt1, 15:00, 01h

    Optimal Window 6 meters :active, 10:00, 05h
    6 meters :opt1, 13:00, 01h

    section Optimal Times (UTC)
    Optimal Window 160 meters :active, 05:00, 06h
    160 meters :opt1, 05:00, 03h

    Optimal Window 80 meters :active, 05:00, 06h
    80 meters :opt1, 08:00, 03h

    Optimal Window 20 meters :active, 14:00, 09h
    Transmit :opt1, 14:00, 01h
    Transmit :opt2, 22:00, 03h
    20 meters :opt1, 21:00, 01h
    
    Optimal Window 60 meters :active, 03:00, 02h
    Optimal Window 60 meters :active, 05:00, 06h    
    60 meters :opt1, 03:00, 02h
    
    Optimal Window 40 meters :active, 01:00, 4h
    Optimal Window 40 meters :active, 05:00, 9h
    40 meters :opt1, 01:00, 2h
    
    Optimal Window 30 meters :active, 00:00, 5h
    Optimal Window 30 meters :active, 05:00, 9h
    30 meters :opt1, 11:00, 3h
    
    Optimal Window 15 meters :active, 15:00, 04h
    15 meters :opt1, 15:00, 02h
    
    Optimal Window 17 meters :active, 15:00, 06h
    17 meters :opt1, 19:00, 01h
    
    Optimal Window 10 meters :active, 15:00, 04h
    10 meters :opt1, 17:00, 01h
    
    Optimal Window 2 meters :active, 16:00, 05h
    2 meters :opt1, 20:00, 01h
    
    Optimal Window 6 meters :active, 15:00, 05h    
    6 meters :opt1, 18:00, 01h

